### ISSUE TITLE
Link back to main article from this repo

### ISSUE THREAD

**Issue by ncouture** [paulgb/wdimtloap#1]
I wish anyone stumbling on this repository by other means than reading the very neat story that documents this code be able to find the article that lead me here (https://paulbutler.org/2022/what-does-it-mean-to-listen-on-a-port/) and perhaps the HN discussion that followed it (https://news.ycombinator.com/item?id=30323865).

Please reference your blog post in a README or equivalent file.

I must say it's true someone who would stumble directly on this code that is curious enough could google a subset of words from the project's description, being:
```
Code accompanying the “what does it mean to listen on a port” blog post.
```

but hyperlinks are so very nice.

Thanks for the great article, I think everyone studying networking should begin by being exposed to everything you outlined so well in this nice article.

**Comment by paulgb** [comment]
Good point, done!
